packaging_format = 2

id = "friendica"
name = "Friendica"
description.en = "Social Communication Server"
description.fr = "Serveur de Communication Social"

version = "2023.05~ynh2"

maintainers = []

[upstream]
license = "AGPL-3.0-only"
website = "http://friendi.ca"
demo = "https://dir.friendica.social/servers"
admindoc = "https://github.com/friendica/friendica/wiki"
userdoc = "https://wiki.friendi.ca/"
code = "https://github.com/friendica/friendica"

[integration]
yunohost = ">= 11.2"
architectures = "all"
multi_instance = true
ldap = true
sso = true
disk = "50M"
ram.build = "150M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"
    
    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.admin]
    type = "user"

    [install.language]
    ask.en = "Choose the application language"
    ask.fr = "Choisissez la langue de l'application"
    type = "select"
    choices = ["de", "en", "es", "fr", "it", "pt"]
    default = "en"

[resources]
    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages = "mariadb-server php7.4-mbstring php7.4-json php7.4-imagick php7.4-xml php7.4-zip php7.4-mysql php7.4-gd php7.4-gmp"

    [resources.database]
    type = "mysql"
